name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        dotnet-quality: preview

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --verbosity normal
