name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    - 'docs/**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |           
          3.1.x
          5.0.x
          6.0.x
          7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
