name: publish-job

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Build
      shell: pwsh
      run: .\build.ps1 --stable=true
      
    - name: Get Release Version
      shell: pwsh
      run: .\build\getReleaseVersion.ps1
      
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.ReleaseVersion }}
        title: ${{ env.ReleaseVersion }}
        prerelease: false
        files: |
          artifacts/packages/*
          
    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.2  
      with:   
        PROJECT_FILE_PATH: src/JiuLing.CommonLibs.csproj  
        NUGET_KEY: ${{secrets.NUGET_API_KEY}} 