name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |             
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore .\src\JiuLing.CommonLibs.sln

      - name: Build
        run: dotnet build .\src\JiuLing.CommonLibs.sln --no-restore -c release

      - name: Test
        run: dotnet test .\src\JiuLing.CommonLibs.sln

      - name: Get version
        uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Create zip
        shell: pwsh
        # 配置【编译后的文件地址】
        run: Compress-Archive -Path .\src\JiuLing.CommonLibs\bin\Release\* -DestinationPath .\src\JiuLing.CommonLibs\bin\Release\JiuLing.CommonLibs_${{ steps.tagName.outputs.tag }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # 配置【README地址】
          body: |
            Release为自动生成，具体内容请查看提交日志，或直接查看[README](https://github.com/JiuLing-zhang/JiuLing.CommonLibs#readme)
          # 配置【zip文件地址】
          files: .\src\JiuLing.CommonLibs\bin\Release\JiuLing.CommonLibs_${{ steps.tagName.outputs.tag }}.zip

      - name: Publish  
        uses: brandedoutcast/publish-nuget@v2.5.2  
        with:   
          PROJECT_FILE_PATH: src/JiuLing.CommonLibs/JiuLing.CommonLibs.csproj  
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
          TAG_COMMIT: false
          INCLUDE_SYMBOLS: true
